### ISSUE TITLE
bro everything is wrong

### ISSUE THREAD

**Issue by bluehalooo** [LightspeedFilterAgent/LightspeedFilterAgent.github.io#1]
it so slow and L A Z Y

bro just make me a developer

i make proxies as a hobby

I MADE THE INTERSTELLAR PROXIES

**Comment by insert-text-here** [comment]
you are moron
A. All ya did was change title names
2. I MAKE PROXIES AS A HOBBY
3. you are too, how is crazygird and duc duc nuk going >:?

**Comment by bluehalooo** [comment]
182.43.12.43

**Comment by bro-my-username-got-blocked** [comment]
hurr
